import type { Store } from "@/types/store";

/**
 * 開発用のダミーデータ。isDevMode() が true のときだけ useStores から使われる。
 * 京都・河原町三条エリアを想定した架空8店舗(以前のプロトタイプ版を新Store型に合わせて再構成)。
 */
export const MOCK_STORES: Store[] = [
  {
    placeId: "mock-1",
    name: "鳥せい 河原町",
    genre: "焼き鳥",
    price: "¥¥",
    photoUrl: "https://picsum.photos/seed/meshi-1/800/1000",
    photoAttribution: "ダミー画像(開発用)",
    lat: 35.0091,
    lng: 135.7701,
    walkMinutes: 4,
  },
  {
    placeId: "mock-2",
    name: "麺屋 十月 三条店",
    genre: "ラーメン",
    price: "¥",
    photoUrl: "https://picsum.photos/seed/meshi-2/800/1000",
    photoAttribution: "ダミー画像(開発用)",
    lat: 35.0088,
    lng: 135.7695,
    walkMinutes: 2,
  },
  {
    placeId: "mock-3",
    name: "京町亭",
    genre: "定食",
    price: "¥",
    photoUrl: "https://picsum.photos/seed/meshi-3/800/1000",
    photoAttribution: "ダミー画像(開発用)",
    lat: 35.0075,
    lng: 135.7706,
    walkMinutes: 3,
  },
  {
    placeId: "mock-4",
    name: "香福記",
    genre: "中華",
    price: "¥¥",
    photoUrl: "https://picsum.photos/seed/meshi-4/800/1000",
    photoAttribution: "ダミー画像(開発用)",
    lat: 35.0102,
    lng: 135.7683,
    walkMinutes: 7,
  },
  {
    placeId: "mock-5",
    name: "たぬき小路 珈琲店",
    genre: "喫茶",
    price: "¥",
    photoUrl: "https://picsum.photos/seed/meshi-5/800/1000",
    photoAttribution: "ダミー画像(開発用)",
    lat: 35.0083,
    lng: 135.7699,
    walkMinutes: 1,
  },
  {
    placeId: "mock-6",
    name: "スパイス工房 三条",
    genre: "カレー",
    price: "¥¥",
    photoUrl: "https://picsum.photos/seed/meshi-6/800/1000",
    photoAttribution: "ダミー画像(開発用)",
    lat: 35.0079,
    lng: 135.7718,
    walkMinutes: 5,
  },
  {
    placeId: "mock-7",
    name: "鮨処 川音",
    genre: "寿司",
    price: "¥¥¥",
    photoUrl: "https://picsum.photos/seed/meshi-7/800/1000",
    photoAttribution: "ダミー画像(開発用)",
    lat: 35.0117,
    lng: 135.7712,
    walkMinutes: 9,
  },
  {
    placeId: "mock-8",
    name: "トラットリア・ソーレ",
    genre: "イタリアン",
    price: "¥¥",
    photoUrl: "https://picsum.photos/seed/meshi-8/800/1000",
    photoAttribution: "ダミー画像(開発用)",
    lat: 35.0056,
    lng: 135.7674,
    walkMinutes: 12,
  },
];
